# Generated by Django 3.2 on 2022-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_fb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trustscore',
            field=models.IntegerField(default=0),
        ),
    ]
