# Generated by Django 3.2 on 2022-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/images/profile/shyam.jpeg', null=True, upload_to='images/profile/'),
        ),
    ]
